title : AKFDS 财经数据科学
author: Albert King
logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  主要介绍开源财经知识

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/akfamily/akfds@main
  path_to_book                : "akfds"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
