title : AKFDS
author: AKFamily
logo: 'ak-logo-large.png'

# Short description about the book
description: >-
  AKFDS 财经数据科学知识库

execute:
  execute_notebooks           : force

# HTML-specific settings
html:
  home_page_in_navbar       : false
  extra_navbar              : Powered by <a href="https://github.com/akfamily">AKFamily</a>

# Launch button settings
launch_buttons:
  notebook_interface          : classic
  binderhub_url               : https://mybinder.org
  jupyterhub_url              : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                       : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                   : "" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                         : https://github.com/akfamily/akfds
  path_to_book                : akfds
  branch                      : main

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
